### ISSUE TITLE
No Module named 'tensorflow.python.keras'

### ISSUE THREAD

**Issue by rushijoshi** [OlafenwaMoses/ImageAI#1]
I am getting an error "ModuleNotFoundError: No module named 'tensorflow.python.keras'".

Traceback (most recent call last):
  File "FirstPrediction.py", line 7, in <module>
    from imageai.Prediction import ImagePrediction
  File "C:\Users\joshir\Downloads\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\
lib\site-packages\imageai\Prediction\__init__.py", line 2, in <module>
    from tensorflow.python.keras.preprocessing import image
ModuleNotFoundError: No module named 'tensorflow.python.keras'

Am I missing anything, I followed instruction and install required packages.

Thanks
RJ

**Comment by rushijoshi** [comment]
Okay I got rid of this error by copying entire keras folder from site-packages to "/tensorflow/python/" folder and after that, it resolved that error but then I got the below error.

File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'C:\Users\joshir\Downl
esnet50_weights_tf_dim_ordering_tf_kernels.h5', errno = 22, error message = 'Inv
alid argument', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

**Comment by OlafenwaMoses** [comment]
@rushijoshi 
It is not advisable to copy the main keras installation folder to "/tensorflow/python/" folder, because Tensorflow already includes it's own version of keras. 

In the second error you encountered after the work around by copying the folder, I notice your file path to the model file is **'C:\Users\joshir\Downlesnet50_weights_tf_dim_ordering_tf_kernels.h5'**, which I suppose should be **'C:\Users\joshir\Downloads\resnet50_weights_tf_dim_ordering_tf_kernels.h5'** .

Also,  version of Tensorflow do you have installed?
