### ISSUE TITLE
Live feed video recording issue

### ISSUE THREAD

**Issue by prashantsondkar** [OlafenwaMoses/ImageAI#183]
Hello
I tried to use Live feed object detection. Saved video runs at very very high speed.

**Comment by OlafenwaMoses** [comment]
This is because you are running ImageAI on a computer that doesn't have NVIDIA GPU. As a result, the detection code is not processed at the same speed as the live feed, meaning it captured only videos frames at very distant intervals, making it look unnecessarily fast. See the link below on solving this.

https://github.com/OlafenwaMoses/ImageAI#real-time-and-high-performance-implementation
