### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by mehrdadscomputer** [OlafenwaMoses/ImageAI#30]
When I run the model, I get this error on this line:
`detector.loadModel()`

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

I did everything according to instruction but encountered that error.
Any idea about the possible reason of the problem?

**Comment by Airyzf** [comment]
hi, do you kown the reason ?

**Comment by OlafenwaMoses** [comment]
Hello, did you ensure you downloaded the correct model file, set the correct model type and set the correct model path to the model file you downloaded?  Ensure all of this is done before running your python code.

**Comment by cowry5** [comment]
Hello, I have same problem. Have you solved it? Could you tell me something about it? Thank you.

**Comment by OlafenwaMoses** [comment]
Hello, I am working on getting a solution to this error.  I will update you all once I find the cause and solution to it. 
For the mean time, you can opt to use YOLOv3 or TinyYOLOv3 instead of the RetinaNet, as the latest version ( 2.0.2) of ImageAI now supports YOLO. All you need to do is install the latest version of ImageAI as instructed in the repository , download the Yolo and/or Tiny Yolo files in the release whose link is below. Remember that if you are using the Yolo model, you must set your model types to YOLOv3 and if you are using the Tiny Yolo model, you must set the model type as TinyYOLOv3.

https://github.com/OlafenwaMoses/ImageAI/releases/tag/1.0

**Comment by musafirsafwan** [comment]
Looks like it has something to do with anaconda. I am getting the same error in conda environment, but not in virtualenv. Error trace given in #35 also shows that the person is using anaconda.

**Comment by pentanol2** [comment]
The solution is easy. Just install the true versions for the requirements. See the following link:
https://imageai.readthedocs.io/en/latest/
