### ISSUE TITLE
CustomObjectDetection - Training progress meaning 480/480

### ISSUE THREAD

**Issue by Troyhard** [OlafenwaMoses/ImageAI#369]
Dear all,

my custom object detection training does not improve, although I am adding new annotated pictures more and more. Now I am wondering, if my code is acutally realising, that there are more and more pics available, because the progress bar looks always like

Epoch 1/200
**5/8** [==============================] - 395s 823ms/step...

I am wondering now, if the "5/8" is the number of trained pictures. Could someone confirm or disconfirm? If it is indeed the number of pictures, which are used for training, why doesnt my code find the remaining hundreds of pics in my train folder?
My code is identical to the hololens-tutorial.

Thanks for any help in advance
Troy

**Comment by rola93** [comment]
5/8 is the number of iterations per epochs. One epoch is achieved when every single training sample pass througth all the network once. Consider that on each iteration batch_size samples pass througth the network (usually for ImageAI batch_size is 4). So there is a strigth relation between the number of samples, batch size and epoch: iterations = number_of_datasets/batch_size

So if you add more data but still see x/8, it means that you are not adding the data properly. Under data_directory there is a folder named `cache` which you need to remove, otherwise the training is lunched over this cached data, and your new training data is not being considered.

Hope that helps!

**Comment by rola93** [comment]
Your welcome! I'm glad it helped! 

It's not well document this part :/ should improve in future versions.

Can you please close the issue?

Thanks!
