### ISSUE TITLE
"anchors" in detection_config.json?

### ISSUE THREAD

**Issue by Rakeshchandrajoshi** [OlafenwaMoses/ImageAI#377]
could anyone explain what the content of detection_config.json file means? Especially, the number representing "anchors" in .json file? 
for Example:
 {
    "labels" : [
        "hololens"
    ],
    "anchors" : [
        [160, 171, 261, 167, 301, 285],
        [78, 86, 104, 69, 138, 105],
        [37, 32, 58, 61, 62, 44]]
}

**Comment by OlafenwaMoses** [comment]
The **detection_config.json** contains the following information:
- **labels:** Names of the objects the model is trained to detect
- **anchors**: Because **ImageAI** uses YOLOv3 which require anchors to effectively generate the best fit **box_points** value that generalize the shape of the object(s) of interest. The anchor values were generated by applying **kmeans** algorithm on the dataset's annotation.
