### ISSUE TITLE
Error on Custome Training Model -  KeyError: 'val_acc'

### ISSUE THREAD

**Issue by Jayuda** [OlafenwaMoses/ImageAI#44]
Hello guys,
after i am follow this tutorial https://github.com/OlafenwaMoses/ImageAI#customtraining 
i run training python but show error : 

KeyError: 'val_acc'

Any information, what that error about ?

I am use : 
Python 3.6
tensorflow 1.9
keras 2.2.0

Thanks

**Comment by Hex-Azir** [comment]
Did you set the batch_size of trainModel()?

**Comment by redaihanyu** [comment]
can you show your code ?

**Comment by mwrouse** [comment]
I am also having this problem, since @Jayuda has not responded (maybe the problem has been solved)? 

But it is still a problem for me: 
```python 
from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("trees")
model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=False)
```


my folder structure is: 
```
trees/train/oaks/*.png
trees/train/maple/*.png

trees/test/oaks/*.png
trees/test/maple/*.png
````

Right now, I have 5 test pictures in each `test` folder, and 7 training images in each `train` folder.

**Comment by OlafenwaMoses** [comment]
The recommended number of train images per object class is 500. See the documentation link below. 
https://imageai.readthedocs.io/en/latest/custom/index.html

**Comment by mwrouse** [comment]
@OlafenwaMoses your comment was not helpful, and counter productive; if you read my post you'd see that I solved my issue by changing the batch size.

I understand that the "recommend" number of training images is 500. But this is not a requirement as that would be ridiculous. 

It is completely unreasonable to assume that someone who is just setting this up for a personal project would have 500+ images of what they want to be able to predict. Sometimes you just need to get things set up first.

**Comment by OlafenwaMoses** [comment]
ImageAI library was built to let developers harness the potentials of state-of-the-art  AI by abstracting the scale of difficulty involved. But since you consider the requirements outrageous, please dive into the details below. 

- ImageAI is powered by deep learning algorithms 
- Deep Learning Algorithms are the only methods to achieving human level performance in intelligence tasks
- Deep Learning requires Big Data to train
- Deep Learning requires hardware with 5X more cost than normal PCs
- Deep Learning involves hundreds to thousands of lines of code ( solved by ImageAI into just 5 lines)  to train a new recognition model. 

Should you get this details a twist, spend the next one week reading extensively on deep learning.

**Comment by mwrouse** [comment]
@OlafenaMoses I didn't say I considered the requirements outrageous. The 500+ images is a recommendation, you said that yourself. 

But saying that it is recommend, referring to the documentation, and closing the issue was, in my opinion, too soon. You didn't give @Jayuda a chance to read what I had posted and see if solved his problem, and (hopefully) reply saying it did.

We both know that 500+ images is not a requirement. Sure, 500+ images is suggested for a very accurate prediction, but it can still function on 10 or so images. It just won't be as accurate as it could.

When first learning how to do this, 500 images is a lot. Especially if you are just messing around to see if it is what you want.

**Comment by andersffs** [comment]
Getting the same error with >900 train images.
