### ISSUE TITLE
Transferlearning only detects new classes

### ISSUE THREAD

**Issue by wootapa** [OlafenwaMoses/ImageAI#460]
Hi Moses. Thank you for making AI easier. 
My question is related to custom model detection and transferlearning. I use yolov3 and wanted to the model to recognize owls as birds. It's understandable it doesn't as owls look funny and non-birdy. I followed the guide here, https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMDETECTION.md. It now detects owls as birds, but nothing else.  I assumed my new model would continue to detect other classes as well. Is this the correct behavior? If so, can models be merged into single model?

**Comment by AbimbolaOO** [comment]
ImageAI does custom object detection using transfer learning. Transfer learning work by training a model on an already trained model (a pretrained model). That is the pretrained model has weights that it has already learned from the previous dataset it was originally trained on. When we used the model to train our own data with transfer learning the pretrained model become fined tuned to our own custom dataset. You might ask why do we even do transfer learning in the first place we do so because it makes our model converge faster at the global minima.
