### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by Alililon** [OlafenwaMoses/ImageAI#536]
I'm having a problem with the code (I just copied the one from https://medium.com/@guymodscientist/image-prediction-with-10-lines-of-code-3266f4039c7a and set the correct path for the sample image). Pycharm already warns me because of 7 different invalid escape sequences and when i execute it, following error message pops up:
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
I didn't find any issue that would solve this, so I'm sorry if it has already been solved, I must've overlooked it.
And just in case it helps, these are the invalid escape sequences:
\B \D \O \P \T \i \s

**Comment by AbimbolaOO** [comment]
Hello  @Alililon, You need to copy the image into the directory where your code is. This would help resolve the issue. 
As an example:

predictions, percentage_probabilities = prediction.predictImage("car.jpg", result_count=5)
for index in range(len(predictions)):
    print(predictions[index] , " : " , percentage_probabilities[index])

You can see here I just wrote the name of my image ('car.jpg') because I made sure it is in the same directory as my code.
