### ISSUE TITLE
When will ImageAI be compatible with Tensorflow 2.0? 

### ISSUE THREAD

**Issue by kgh475926** [OlafenwaMoses/ImageAI#553]
When will ImageAI be compatible with Tensorflow 2.0? The main page says coming soon but we are approaching July 2020.

**Comment by Leterax** [comment]
This would be awesome!

**Comment by rjelbert** [comment]
Just wondering if this project is now abandoned. The last update in master was 9 months ago. It would be a shame if it is but our new DS environment is TF2 so we'll have to use another set of tools.

**Comment by kgh475926** [comment]
I'm wondering the same thing too. I suppose a lot of projects that have used ImageAI will shift to use tools which is sad.

**Comment by OlafenwaMoses** [comment]
Hi everyone, I will like to express my sincere apologies for the long wait on this. The project has not been abandoned. 

Work is ongoing to release the TF 2.0 compatible version and will be available before year 2020 elapse. The delay has been due to other projects I am working on and my everyday job. Also, I am making efforts to put in place an organized, well structured system for consistent maintenance and improvement of the project.

**Comment by kgh475926** [comment]
Hello! I hope you are doing well during this difficult time. Thank you for the update. I'm looking forward to see the compatibility of the coming release 😀

**Comment by Pikamander2** [comment]
Hey @OlafenwaMoses - thanks for all your hard work on this project.

Not to rush you, but are you still on track to release a TF 2.0 compatible version by the end of the year? I'm trying to set up the current version on my machine, but it's been a nightmare due to all of the outdated requirements. If it's still expected to be released by the end of the year, then I might just wait until then. Otherwise, I'll have to look for something else in the meantime.

Again, no pressure here, just looking for an honest assessment of the release schedule.

**Comment by AlucardNosferatu** [comment]
The newest Keras 2.x (2.4.3) require TF 2.2 or newer, plz give the specific version of Keras, Thank you!

**Comment by OlafenwaMoses** [comment]
Hello everyone, a new version has been released with support for TF 2.4.0. Kindly follow the instructions detailed in the documentation linked below.

https://imageai.readthedocs.io/en/latest/index.html#installing-imageai

**Comment by cross-hello** [comment]
> Hello everyone, a new version has been released with support for TF 2.4.0. Kindly follow the instructions detailed in the documentation linked below.
> 
> https://imageai.readthedocs.io/en/latest/index.html#installing-imageai

Thanks for your work.
