### ISSUE TITLE
Error in incremental training of custom detection with new classes

### ISSUE THREAD

**Issue by cpenalozagFM** [OlafenwaMoses/ImageAI#568]
Hi,

I am trying to continue the training using a pretrained model but I am getting the following error:

> ValueError: Layer #249 (named "conv_81"), weight <tf.Variable 'conv_81/kernel:0' shape=(1, 1, 1024, 33) dtype=float32> has shape (1, 1, 1024, 33), but the saved weight has shape (27, 1024, 1, 1).

My code looks like this:
```
trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory='dataset')
trainer.setTrainConfig(object_names_array=["class2", "class2", "class3", "class4", "class5", "class6"],
                       batch_size=4, num_experiments=10, train_from_pretrained_model="model.h5")
trainer.trainModel()
```

The file model.h5 is the best version of the first training session. I have included two new classes this time, could this be the problem?

**Comment by Combinacijus** [comment]
I can confirm that it's happening because you added more classes. I'm not sure if this is a bug or just the way neural networks works because you want for network to have different structure/shape. I have found similar [issue](https://github.com/pjreddie/darknet/issues/1088) on darknet github which seems to be solved. Darknet provides more customization but it's also harder to use.

And for a **workaround**:
If you have changed the number of classes you can train from given [pretrained model pretrained-yolov3.h5](https://github.com/OlafenwaMoses/ImageAI/releases/tag/essential-v4) and then continue training from your new model with all the classes

Or maybe (I haven't tested it) if you know that you'll need to add more classes you could train your model with dummy classes and dummy data. And change it when needed for e.g you start with 
`object_names_array=["class1", "class2", "dummy1", "dummy2", "dummy3", "dummy4"]` 
and when needed change to 
`object_names_array=["class1", "class2", "class3", "class4", "dummy3", "dummy4"] `

PS You also added two "class2"
