### ISSUE TITLE
google colab always disconnect

### ISSUE THREAD

**Issue by refaeldimri** [OlafenwaMoses/ImageAI#570]
i try to train but google colab always disconnect and the running does not finish.
i try to add script to browser to connect every 1 minute, it does not help me..
TNX

**Comment by AbimbolaOO** [comment]
Hello @refaeldimri, 
I think you should check if you are on a GPU or not because this a kind of problem that normally occurs when trying to train a deep learning model using just the CPU on google colab. To set you your runtime such that it is using a GPU click on runtime on colabs menu. Then a  drop-down menu would show up and in that click change runtime type. After doing all that just restart your notebook. Voila, everything starts to work properly.

**Comment by refaeldimri** [comment]
TNX @AbimbolaOO . i think u right, i forget to do it.

**Comment by refaeldimri** [comment]
i did it. it is better, but still disconnect and can not connect GPU always. if i mount my drive, is the data saved? how can i run from the point it stopped?

**Comment by OlafenwaMoses** [comment]
You might want to post this issue in the **Colab Tools** repo.

https://github.com/googlecolab/colabtools/issues
