### ISSUE TITLE
How to change color of bounding box based on some condition?

### ISSUE THREAD

**Issue by abhishek1222017** [OlafenwaMoses/ImageAI#571]
Hi Everyone,
I am detecting car in the images using detector.CustomObjects(car=True). Based on distance, I want to change it's color from default to red. How can I do it? Any help is highly appreciable. It is urgent

**Comment by firmamentone** [comment]
Hi, 
For this problem, I modify the imageAI source. (Are there any function or parameters can set the color? )

in the "detectObjectsFromImage( )", the function "draw_boxes_and_caption( )" are used to draw the bondingbox on the detected frame. (image) 

check the "draw_boxes_and_caption( )", we could assign the value to variable "class_color" according to the "v_labels" directly.

![draw_boxes_and_caption](https://user-images.githubusercontent.com/5135399/90521019-9f2e9780-e19c-11ea-9b75-1c12b56c6a8c.png)

The current design uses a table self.label_color() to assign the value for " "class_color" but the table is created by random number. That's why the default color is random.
![random](https://user-images.githubusercontent.com/5135399/90524713-fcc4e300-e1a0-11ea-8f5c-e27b8ea60ae8.png)
