### ISSUE TITLE
Can't use ImageAI with latest versions

### ISSUE THREAD

**Issue by Oliviero-P** [OlafenwaMoses/ImageAI#656]
Hello!

I'm trying to get the ImageAI to work, following the ZeroToMastery Python developer course - it did give me some errors with downloading the specific versions of the modules needed, like 
`Could not find a version that satisfies the requirement scipy==1.4.1 (from imageai)`

So I just downloaded the latest versions of all modules, and now it's giving me this issue

`'ImagePrediction' object has no attribute 'setModelTypeAsMobileNetV2'`

How do I fix this?

Thanks!

**Comment by OlafenwaMoses** [comment]
use `ImageClassification` class instead.

```
from imageai.Classification import ImageClassification
```

https://imageai.readthedocs.io/en/latest/prediction

**Comment by Oliviero-P** [comment]
Thanks!

Now it's saying that there is no module imageai.Classification

Here's the packages I can reach

```
Help on package imageai:

NAME
    imageai

PACKAGE CONTENTS
    Detection (package)
    Prediction (package)
```
And with Prediction it's still the same as before, and if I try with Detection, I get this:

`module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`

Now I'll try to disintall imageai, and the other packages, and try to reinstall them again

**Comment by Oliviero-P** [comment]
Found the answer! I was running python 3.9, tried it with python 3.8 and it works!

Thanks!

**Comment by s-andrews** [comment]
Just to comment on this since I also hit this issue - the problem here is that imageai has a hard dependency on scipy==1.4.1 (which is quite  a way off the latest scipy release).  This scipy version is old enough that there isn't a binary wheel file for python3.9 or 3.10 on pypi - 3.8 is the latest.  This means that when you try to install pip will attempt to compile from source, and this fails.  ImageAI continues and looks like it's installed but you get a broken partial installation.

The ultimate fix for this would be to make the code work with a more recent scipy otherwise windows users are going to be stuck on python3.8.
